
CC = gcc
FLAGS = 

all: ofiles tests

ofiles: strings/bstring.o lists/blistd.o lists/blists.o maps/bhash.o func/bfunc.o memory/bmem.o

strings/bstring.o: strings/bstring.c
	$(CC) $(FLAGS) -c strings/bstring.c -o strings/bstring.o

lists/blistd.o: lists/blistd.c
	$(CC) $(FLAGS) -c lists/blistd.c -o lists/blistd.o

lists/blists.o: lists/blists.c
	$(CC) $(FLAGS) -c lists/blists.c -o lists/blists.o

maps/bhash.o: maps/bhash.c
	$(CC) $(FLAGS) -c maps/bhash.c -o maps/bhash.o

memory/bmem.o: memory/bmem.c
	$(CC) $(FLAGS) -c memory/bmem.c -o memory/bmem.o

func/bfunc.o: func/bfunc.c
	$(CC) $(FLAGS) -c func/bfunc.c -o func/bfunc.o

test: tests
	@./test

tests: strings/bstring.o lists/blistd.o lists/blists.o memory/bmem.o maps/bhash.o test.c
	$(CC) $(FLAGS)  strings/bstring.o lists/blistd.o lists/blists.o memory/bmem.o maps/bhash.o test.c -o test

clean: 
	-rm -rf test
	-rm -rf func/*.o
	-rm -rf lists/*.o
	-rm -rf maps/*.o
	-rm -rf memory/*.o
	-rm -rf strings/*.o

# Generated by Ruby2Make
